version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/acdsampleapp

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stopServer.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startServer.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/validate.sh
      timeout: 300
      runas: root